### PR TITLE
Add a cache for decrypted values

### PR DESCRIPTION
**Pull request by stlava**
Addresses #239

### CODE REVIEW

**Comment by rnelson0** [comment]
@stlava I've fixed the tests, if you can rebase this to make sure it passes.

I do like the idea in #239 of an option to control whether caching is enabled. Do you think you could add that to this PR?

**Comment by stlava** [comment]
@rnelson0 I added an option. It didn't seem very necessary to include this part of the sub-command options but let me know.

**Comment by stlava** [comment]
@rnelson0 I work with @diranged and took over the ticket. I deployed this yesterday at 22:00 utc.  Here's the trend: 
average config retrieval times

**Comment by rnelson0** [comment]
Oh, cool! That's noticeable, but not that drastic of a change. Is your compilation time coming from something else or does the caching need more work?

Happy to merge it, thanks for the contribution!

**Comment by stlava** [comment]
Adding the caching was a step forward for us to cut down the compilation time but as you pointed out the rest of our time does come from us hitting other external resources. Thanks for getting this in!

**Pull request merged**
