### PR TITLE
fix pkcs7 plugin option defaults

### LINKED ISSUE #101: Public/private keys undefined for Vagrant
For some reason when I run a puppet script using hiera-eyaml the default values for the public and private keys are undefined. If I run a provisioning script i get:

```
  Error: pkcs7_public_key is not defined at /tmp/vagrant-puppet-1/manifests/default.pp:1 on node ubuntu-server-12042-x64-vbox4210.home
  Wrapped exception:
  pkcs7_public_key is not defined
```

You can reproduce the issue by using the test case project I've prepared and running:

```
  $ git clone git@github.com:rgladwell/test-hiera-eyaml-vagrant.git
  $ vagrant up
```

This can be fixed by explicitly setting the private keys in the `hiera.yaml` configuration file:

```
 :eyaml:
    :datadir: hiera/
        :pkcs7_public_key:  ./keys/public_key.pkcs7.pem
        :pkcs7_private_key:  ./keys/private_key.pkcs7.pem
```

### PR DESCRIPTION
**Pull request by jhoblitt**
Resolves #101

### CODE REVIEW

**Comment by elyscape** [comment]
Instead of pinning to 3.7, we should work out why the plugin doesn't work with Puppet 4. If we do have to pin temporarily, it should be to 3.0 instead of 3.7.

**Comment by jhoblitt** [comment]
@elyscape Are you concerned that all releases of 3.7.x might be removed from Gems?  The version constraint is to 3.x, not 3.7.x.

**Comment by elyscape** [comment]
Pinning to 3.0 sets the version constraint to 3.x. Pinning to 3.7 sets the version constraint to 3.x with x >= 7.

**Comment by jhoblitt** [comment]
Indeed.  Why is that a concern?

**Comment by elyscape** [comment]
There are people on older versions of Puppet.

**Comment by jhoblitt** [comment]
And the Gemfile doesn't effect them because the gemspec doesn't use the Gemfile.  Its only for development and CI.

I repushed this morning with the defacto PUPPET_GEM_VERSION and added the puppet version into the travis matrix.

**Comment by elyscape** [comment]
That works better, but IMO we should also test with Puppet 3.2, 3.4, and 3.6, as those were versions with Puppet Enterprise releases and therefore most likely to be still widely used.

**Comment by jhoblitt** [comment]
That's orthogonal to this bugfix.  Originally, the only changes to the CI configuration included in this PR are what was needed so the tests would actually pass.  I've since added puppet 4.0 in an allowed failure mode due to your objection.  I feel that anything beyond this needs to be a separate PR.

**Comment by elyscape** [comment]
A fair point.

**Comment by jhoblitt** [comment]
ping?

**Comment by jhoblitt** [comment]
ping

**Comment by elyscape** [comment]
@TomPoulton, please review.

**Comment by vinzent** [comment]
closing due to age and no progress with this PR.

**Comment by jhoblitt** [comment]
@vinzent #101 is still open -- do you believe this problem has been resolved?

**Comment by vinzent** [comment]
@jhoblitt no I don't believe. but nobody cared to update the PR since 2015-10-16. 

feel free to update it with master the current master branch and create a new PR. I would be very welcome.

**Pull request closed without merging**
