### PR TITLE
Modify edit command to not recrypt unchanged values

### PR DESCRIPTION
**Pull request by cosmincojocar**
I rebased the PR #201 initially created by @dianac10.

@rnelson0 @nfagerlund Please could you review the changes? We plan to open source soon a plugin for Microsoft KeyVault. Without this fix, we are forced to use a forked version, which we really want to avoid.

cc @brndkfr @maximbaz-microsoft

### CODE REVIEW

**Comment by nfagerlund** [comment]
I can't review this, as I don't know the code well enough.

**Comment by rnelson0** [comment]
I definitely don't know how to review this properly. I do notice there's no additional tests. Can a new test for this be added at all?

**Comment by cosmincojocar** [comment]
@rnelson0 @nfagerlund I will add some tests next week. It's not clear to me who is the active maintainer of this repository, I picked you guys due to the last commits. Please loop in other maintainers if required. Thanks

**Comment by cosmincojocar** [comment]
@rnelson0 @TomPoulton @nfagerlund I added two test scenarios for this fix. eyaml should encrypt only when the plaintext is modified not when some random text is changed in the file. The current behavior of eyaml is to rencrypt again all plain texts.

**Comment by cosmincojocar** [comment]
@rnelson0 Any progress on this PR?

**Comment by rnelson0** [comment]
I have to rely on @TomPoulton for this, sorry.

**Comment by cosmincojocar** [comment]
@TomPoulton @rnelson0 Any progress with the review? It would be grate if you could merge it if there aren't any concerns.

**Comment by maximbaz-microsoft** [comment]
Soon we are going to "celebrate" 1 year mark of us trying to get these contributions reviewed and merged... just saying 😛

**Comment by nibalizer** [comment]
I've read this and I add my name to the list of people who don't feel comfortable green-button-ing. @cosmincojocar @maximbaz-microsoft It seems like you are the community members who do understand hiera-eyaml the best, would you like to join @voxpupuli and take over maintenance?

**Comment by rnelson0** [comment]
@cosmincojocar The tests have been updated and there's a few more changes since you submitted the PR. I think we're pretty confident now that with the tests working, if you rebase and it passes, there's no issue with merging it.

From the perspective of releasing a new version, this is not a breaking change, correct?

**Comment by cosmincojocar** [comment]
@rnelson0 The branch is rebased. I confirm that this is only a bug fix, no breaking change.

**Comment by cosmincojocar** [comment]
@rnelson0 It seems that the puppet 4.x tests are broken also on master. There are various warnings due to to hiera update from  version 3 to version 5. 

In order to have it running with 4.x the following fixes are required in a different PR:
- hiera and hiera_* functions need to be replaced by lookup 
- hiera.yaml need to be updated to version 5

It'll require most likely two sets of tests, one for puppet 3.8 and another one for 4.x.

**Comment by rnelson0** [comment]
@cosmincojocar I fixed the tests, if you want to rebase and push again, please.

**Comment by cosmincojocar** [comment]
@rnelson0 done, the tests are now green.

**Pull request merged**
