### PR TITLE
Use Hiera Backend API v2 when possible

### PR DESCRIPTION
**Pull request by spacepants**
Puppet `4.9.x` breaks eyaml lookups due to hiera-eyaml's reliance on [the deprecated v1 Hiera Backend API](https://tickets.puppetlabs.com/browse/PUP-7215?focusedCommentId=408366&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-408366). This updates the `Eyaml_backend` to use the v2 API when the version of Hiera installed supports it, and should be backwards compatible with older versions.

Note: I needed to include @rnelson0's Travis and Gemfile update in order to pass the build.

@TomPoulton @sihil please let me know if this needs anything else. Thanks!

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @spacepants, thanks for the PR. Can you please rebase?

**Comment by kenyon** [comment]
I don't know if this is still needed, but I did the rebase.

**Comment by alexjfisher** [comment]
> I don't know if this is still needed, but I did the rebase.

I doubt it.  See https://github.com/voxpupuli/hiera-eyaml/pull/299#issuecomment-591421805

**Comment by ghoneycutt** [comment]
Closing due to inactivity and uncertainty if it is even still needed. Please feel free to re-open.

**Pull request closed without merging**
