### PR TITLE
Modify recrypt command to allow recrypting file with different encryp…

### PR DESCRIPTION
**Pull request by cosmincojocar**
I rebased the PR #211  initially created by @dianac10. 

@rnelson0 @nfagerlund  Please could you review the changes? We plan to open source soon a plugin for Microsoft KeyVault. Without this fix, we are forced to use a forked version, which we really want to avoid. 

cc @brndkfr @maximbaz-microsoft

### CODE REVIEW

**Comment by cosmincojocar** [comment]
@rnelson0  Should we add tests also for this scenario?

**Comment by rnelson0** [comment]
Yes, tests are definitely recommended.

**Comment by cosmincojocar** [comment]
@rnelson0 I added more tests for recrypt command specifically for the opitons introduced by this PR. Initially the text is encrypted with **PKCS7`**, then rencrypted  with a different encryption **plaintext** and finally rencrypted back to **PKCS7**.  We introduced the **-d** (_change_encryption_) option.

**Comment by cosmincojocar** [comment]
@rnelson0 Looking forward to you feedback. Do you need more details to be able to review the PR?

**Comment by rnelson0** [comment]
@cosmincojocar I've reached out to @TomPoulton for some verification. This looks good to me, but we (VP) have just recently accepted this gem so I want to make sure I'm not missing something obvious, and to make sure that the updated tests are properly validating this (I think we need to change the test output so it's more clear which tests are running so we know a test isn't skipped - but unrelated to this PR).

**Comment by cosmincojocar** [comment]
@rnelson0 Any progress on this PR?

**Comment by rnelson0** [comment]
I have to rely on @TomPoulton for this, sorry.

**Comment by TomPoulton** [comment]
Hi all, from what I can tell by glancing at the logs, it looks like there's an incompatibility between the `json_pure v2.0.1` gem and ruby `1.8.7`

I imagine we're going to run into these problems more are more, so I suppose we should decide whether we want to "officially" support `1.8.7`?

**Comment by rnelson0** [comment]
@TomPoulton I created #238 for version support. In the meantime, can you review the code itself for possible issues, either technical or that would affect the roadmap?

**Comment by cosmincojocar** [comment]
@TomPoulton @rnelson0 Any progress with the review? It would be grate if you could merge it if there aren't any concerns.

**Comment by cosmincojocar** [comment]
@rnelson0 Also this branch is rebased.

**Comment by rnelson0** [comment]
@cosmincojocar This should be good to rebase again, as well!

**Comment by cosmincojocar** [comment]
@rnelson0 done, the tests are now green.

**Comment by rnelson0** [comment]
Hooray! Thanks for your patience!

**Comment by kevgreen-ebay-com** [comment]
Personal, rather than company opinion, but it is possible that the way this is implemented has broken GPG encryption causing the default to always be PKCS7 on recrypt, irrespective of what is listed in the various config files. It certainly appears that 3.0.0 onwards is affected by this problem.

**Pull request merged**
