### PR TITLE
Permit reading private key from environment variable

### PR DESCRIPTION
**Pull request by nferch**
per #284

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @nferch, thanks for the PR. Can you add some documentation to the README.md?

**Comment by nferch** [comment]
> Hi @nferch, thanks for the PR. Can you add some documentation to the README.md?

Done.

**Comment by nferch** [comment]
@alexjfisher @binford2k @crayfishx @mmerfort any opportunity for a review? thanks.

**Comment by bastelfreak** [comment]
thanks for the PR!

**Pull request merged**
