### PR TITLE
Performance bug: unnecessary double-decryption of blocks

### PR DESCRIPTION
**Pull request by peculater**
This line is duplicated with no side-effect I can find.  The comparable chunk dealing with string decrypting only has one call, as do both encryption chunks.  Looks like a copy-and-paste-o.  Removing it passes all tests (including puppet ones after PR #181) and gives me about a ~15% improvement in overall block decryption speed with the particular eyaml file I care about.

### CODE REVIEW

**Comment by sihil** [comment]
Does look like a copy and paste error - mine by all accounts. Good spot @peculater.

:+1:

**Comment by peculater** [comment]
Rebased this against master now that the test-passing stuff is in.  Yay for green checks. :-)

**Comment by mattkenn4545** [comment]
Should this be closed?

**Comment by gdubicki** [comment]
You mean merged, @mattkenn4545 ? If so then I am +1 for it.

**Pull request merged**
