### PR TITLE
Upgrading trollop to optimist to remove deprecation warnings

### LINKED ISSUE #267: DEPRECATION - trollop gem is deprecated, need to switch to optimist
Every time I run the eyaml command line client I get a deprecation warning:

```
[DEPRECATION] This gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.
```

https://www.ruby-toolbox.com/projects/trollop
http://manageiq.github.io/optimist/

### PR DESCRIPTION
**Pull request by chadlyon**
This may break ruby <= 1.8 but I am unable to test this since I don't know how to set up a 1.8 env.

Fixes #267

### CODE REVIEW

**Comment by bastelfreak** [comment]
From my point of view this looks fine, but I would like to get feedback from another reviewer. Thanks for the contribution @chadlyon !

**Comment by tuxmea** [comment]
According to optimist website, ruby 1.8 is still OK. I assume we can remove the backwards-incompatible flag.

**Comment by chadlyon** [comment]
I tried to test in a 1.8 env and I got other incompatibilities:
`
Gem::InstallError: rake requires Ruby version >= 2.0.0.
An error occurred while installing rake (12.3.1), and Bundler cannot continue.
Make sure that `gem install rake -v '12.3.1'` succeeds before bundling.

In Gemfile:
  rake
`
...and then commenting out rake:
`
Gem::InstallError: ffi requires Ruby version >= 1.9.
An error occurred while installing ffi (1.9.25), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.25'` succeeds before bundling.

In Gemfile:
  aruba was resolved to 0.6.2, which depends on
    childprocess was resolved to 0.9.0, which depends on
      ffi
`

...then I gave up. It seems that the test suite is incompatible with 1.8.

**Comment by ghoneycutt** [comment]
Do we care about ruby 1.8 from Puppet 3? This seems good to merge.

**Comment by bastelfreak** [comment]
Ruby 1.8 and Puppe 3 are EOL. We don't support it anymore.

**Comment by chadlyon** [comment]
When do you guys plan on cutting a release so that I can see these warning finally go away?

**Comment by franciscodelgadodev** [comment]
Any update about releasing this? Seems like the fix is already in place but it was never released to rubygems.

**Pull request merged**
