### PR TITLE
Release 3.5.0

### PR DESCRIPTION
**Pull request by robbat2**
Please fast-forward merge and include the v3.5.0 tag from my repo; or otherwise generate a new gpg-signed tag.

### CODE REVIEW

**Review by kenyon — COMMENTED** [review]
Looks like it should be v4.0.0 since there are breaking changes.

**Comment by robbat2** [comment]
@bastelfreak  your opinion on calling this v3.5.0 vs v4.0.0?

The changelog autogenerator said it was a "breaking change" based on your PR tags on https://github.com/voxpupuli/hiera-eyaml/pull/351
However under Semantic Versioning rules, I don't think it actually fits:

https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

The API did *NOT* change, only the dependency did, so it's a minor bump, not a major bump

**Comment by robbat2** [comment]
@bastelfreak bump; re what version should this be called; it's not really breaking changes, but I can bump it to 4.0.0 if you want anyway.

**Comment by bastelfreak** [comment]
next release hast to be 4.0.0 because there are backwards incompatible changes. I raised a new PR at https://github.com/voxpupuli/hiera-eyaml/pull/381

**Pull request closed without merging**
